# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: test upload with TF

on:
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  upload:
    runs-on: ubuntu-latest
    name: Upload file to Devops Config
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Upload data
        uses: ./actions/sn_devops/upload_folder # Uses an action in the root directory
        id: upload
        with:
          instance-url: ${{ secrets.SN_INSTANCE }}
          devops-integration-user-name: ${{ secrets.SN_USER }}
          devops-integration-user-password: ${{ secrets.SN_PASSWORD }}
          application: "Globex-Website-Front-End"
          target: "component"
          folder-path: "terraform"
          recursive: true
          data-format: "tf"
          auto-validate: true
          publish-option: "publish_valid"
          name-path: ""
      # Use the output from the `hello` step
      - name: Get the changeset number
        run: echo "Changeset number ${{ steps.upload.outputs.changeset }}"
  validate:
    runs-on: ubuntu-latest
    name: tests
    needs: [upload, build]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: ServiceNow DevOps Unit Test Results
        uses: ServiceNow/servicenow-devops-test-report@dev
        with:
          devops-integration-user-name: ${{ secrets.SN_USER }}
          devops-integration-user-password: ${{ secrets.SN_PASSWORD }}
          instance-url: ${{ secrets.SN_INSTANCE }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: 'Test'
          xml-report-filename: 'target'
  deploy:
    name: Deploy
    needs: validate
    runs-on: ubuntu-latest
    steps:     
      - name: ServiceNow Change
        uses: ServiceNow/servicenow-devops-change@v2.0.0
        with:
          devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
          devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: 'Deploy'
          change-request: '{"setCloseCode":"true","attributes":{"short_description":"Automated Software Deployment","description":"Automated Software Deployment.","assignment_group":"a715cd759f2002002920bde8132e7018","implementation_plan":"Software update is tested and results can be found in Test Summaries Tab; When the change is approved the implementation happens automated by the CICD pipeline within the change planned start and end time window.","backout_plan":"When software fails in production, the previous software release will be re-deployed.","test_plan":"Testing if the software was successfully deployed"}}'
          interval: '100'
          timeout: '3600'
          changeCreationTimeOut: '3600'
          abortOnChangeCreationFailure: true
          abortOnChangeStepTimeout: true
